import { describe, it, expect } from 'vitest';
import { generateToolDoc, inferLayer, extractParamRows } from '../../scripts/gen-tool-docs.mjs';

// 项目待办 :154 — gen-tool-docs.mjs 纯函数测试

const SAMPLE_TOOL = {
  name: 'test_tool',
  group: 'core',
  description: '测试工具。foo: 做 foo。bar: 做 bar。',
  inputSchema: {
    type: 'object',
    properties: {
      action: { type: 'string', enum: ['foo', 'bar'], description: '操作类型' },
      project_path: { type: 'string', description: 'Godot 项目目录路径' },
      count: { type: 'number', description: '数量' },
    },
    required: ['action'],
  },
  requiredParams: ['action'],
  optionalParams: ['project_path', 'count'],
  readonly: false,
  longRunning: true,
  securityLevel: 'guarded',
  needsGodot: true,
  needsEditor: false,
  riskDistribution: { read: 1, write: 1, destructive: 0, process: 0 },
};

describe('gen-tool-docs — inferLayer', () => {
  it('editor 层: needsEditor=true', () => {
    expect(inferLayer({ needsEditor: true, needsGodot: true })).toBe('editor');
  });

  it('bridge 层: group=game', () => {
    expect(inferLayer({ group: 'game', needsEditor: false })).toBe('bridge');
  });

  it('bridge 层: name=runtime', () => {
    expect(inferLayer({ name: 'runtime', group: 'core', needsEditor: false })).toBe('bridge');
  });

  it('headless 层: needsGodot + 非 editor/bridge', () => {
    expect(inferLayer({ needsGodot: true, needsEditor: false, group: 'core' })).toBe('headless');
  });
});

describe('gen-tool-docs — extractParamRows', () => {
  it('action 排首位,required 标 ✓', () => {
    const rows = extractParamRows(SAMPLE_TOOL);
    expect(rows[0].name).toBe('action');
    expect(rows[0].required).toBe('✓');
  });

  it('optional 参数 required 为空', () => {
    const rows = extractParamRows(SAMPLE_TOOL);
    const projectPath = rows.find(r => r.name === 'project_path');
    expect(projectPath?.required).toBe('');
  });

  it('action enum 超 3 项只标 enum (N 项) 不全列', () => {
    const tool = {
      ...SAMPLE_TOOL,
      inputSchema: {
        ...SAMPLE_TOOL.inputSchema,
        properties: {
          action: { type: 'string', enum: ['a', 'b', 'c', 'd', 'e'] },
        },
      },
    };
    const rows = extractParamRows(tool);
    expect(rows[0].type).toBe('enum (5 项)');
  });

  it('enum ≤ 3 项全列(非 action 参数)', () => {
    const tool = {
      ...SAMPLE_TOOL,
      inputSchema: {
        ...SAMPLE_TOOL.inputSchema,
        properties: {
          action: { type: 'string', enum: ['foo', 'bar'] },
          mode: { type: 'string', enum: ['x', 'y'], description: '模式' },  // 非 action,2 项
        },
      },
    };
    const rows = extractParamRows(tool);
    const mode = rows.find(r => r.name === 'mode');
    expect(mode?.type).toBe('enum: x | y');
  });
});

describe('gen-tool-docs — generateToolDoc', () => {
  const doc = generateToolDoc(SAMPLE_TOOL, '0.28.0');

  it('含标题 + 描述', () => {
    expect(doc).toContain('# test_tool');
    expect(doc).toContain('测试工具');
  });

  it('含属性表(层/安全/Godot/editor/只读/长耗时)', () => {
    expect(doc).toContain('headless');
    expect(doc).toContain('guarded');
    expect(doc).toContain('需要 Godot');
    expect(doc).toContain('长耗时');
  });

  it('含 Actions section(从 action enum)', () => {
    expect(doc).toContain('## Actions');
    expect(doc).toContain('`foo`');
    expect(doc).toContain('`bar`');
  });

  it('含 Parameters 表', () => {
    expect(doc).toContain('## Parameters');
    expect(doc).toContain('`action`');
    expect(doc).toContain('`project_path`');
    expect(doc).toContain('`count`');
  });

  it('含风险分布', () => {
    expect(doc).toContain('## 风险分布');
    expect(doc).toContain('读 1');
    expect(doc).toContain('写 1');
  });

  it('含 AUTO-GENERATED 页脚 + matrix 版本', () => {
    expect(doc).toContain('AUTO-GENERATED by scripts/gen-tool-docs.mjs');
    expect(doc).toContain('v0.28.0');
  });

  it('无 action 的工具不生成 Actions section', () => {
    const noActionTool = {
      ...SAMPLE_TOOL,
      inputSchema: { type: 'object', properties: { project_path: { type: 'string' } } },
    };
    const d = generateToolDoc(noActionTool, '0.28.0');
    expect(d).not.toContain('## Actions');
  });

  it('幂等: 同输入产出相同输出', () => {
    const doc1 = generateToolDoc(SAMPLE_TOOL, '0.28.0');
    const doc2 = generateToolDoc(SAMPLE_TOOL, '0.28.0');
    expect(doc1).toBe(doc2);
  });
});

describe('gen-tool-docs — docs/tools/ 覆盖完整性', () => {
  it('每个 TOOL_NAMES(help.ts)在 docs/tools/ 有对应 .md', async () => {
    const { readdirSync } = await import('fs');
    const { join } = await import('path');
    const docsDir = join(process.cwd(), 'docs', 'tools');
    const files = readdirSync(docsDir).filter(f => f.endsWith('.md')).map(f => f.replace('.md', ''));

    // TOOL_NAMES 必须与 help.ts:16-24 一致(改动 help.ts 时同步更新此处)
    const TOOL_NAMES = [
      'android', 'animation', 'animation_track', 'animtree', 'asset', 'audio', 'blender',
      'cpp', 'csv_to_resources', 'docs', 'editor', 'game', 'godot_advanced_tool',
      'godot_get_context', 'godot_list_dynamic_routes', 'godot_list_instances',
      'godot_select_instance', 'help', 'load_skill', 'manage_tools', 'material', 'nav',
      'particles', 'physics', 'profiler', 'project', 'runtime', 'runtime_assert', 'scene',
      'screenshot', 'script', 'self_update', 'signal', 'testing', 'tilemap', 'ui',
      'validation', 'workflow',
    ];
    const missing = TOOL_NAMES.filter(n => !files.includes(n));
    expect(missing).toEqual([]);
  });
});
