// src/tools/cpp-templates.ts
// GDExtension 脚手架模板 + 渲染。纯字符串生成,无 fs/网络副作用。
// 模板内容对齐 godot-cpp 官方 example(test/src/example.*、test/SConstruct、test/project/example.gdextension)。

export interface ScaffoldCtx {
  className: string;   // PascalCase,如 Example
  parentClass: string; // Godot 内置类,如 Node
  parentInc: string;   // godot-cpp include 文件名(snake_case),如 node → <godot_cpp/classes/node.hpp>
  lib: string;         // libname = className.toLowerCase(),如 example
  godotVersion: string; // 4.4 / 4.5 / 4.6
}

export interface ScaffoldFile {
  path: string;    // 相对工程根,如 src/Example.h
  content: string;
}

// ─── 白名单 / 常量 ────────────────────────────────────────────────────────────

// godot-cpp 的 class 头文件由绑定生成器在用户构建 godot-cpp 时产出(<godot_cpp/classes/<file>.hpp>),
// 命名规则:PascalCase → snake_case;尾随单个数字连写(node2d);字母后接数字加分隔(character_body_2d)。
// control.hpp 经 godot-cpp/test/src/example.h 验证,其余遵循同一规则。
export const PARENT_CLASS_WHITELIST: Record<string /* PascalCase */, string /* include file */> = {
  Node:            'node',
  Resource:        'resource',
  RefCounted:      'ref_counted',
  Control:         'control',
  Node2D:          'node2d',
  Node3D:          'node3d',
  Sprite2D:        'sprite2d',
  Camera2D:        'camera2d',
  Camera3D:        'camera3d',
  Area2D:          'area2d',
  Area3D:          'area3d',
  CharacterBody2D: 'character_body_2d',
  CharacterBody3D: 'character_body_3d',
  RigidBody2D:     'rigid_body_2d',
  RigidBody3D:     'rigid_body_3d',
};

export const SUPPORTED_GODOT_VERSIONS = ['4.4', '4.5', '4.6'] as const;

// PascalCase:大写字母开头,后接字母/数字。拒绝小写开头/连字符/数字开头/下划线。
export const CLASS_NAME_RE = /^[A-Z][A-Za-z0-9]*$/;

// ─── 渲染 ─────────────────────────────────────────────────────────────────────

export function renderScaffold(ctx: ScaffoldCtx): ScaffoldFile[] {
  const { className: cls, parentClass: parent, parentInc, lib, godotVersion: ver } = ctx;

  const headerH = `#pragma once

#ifdef WIN32
#include <windows.h>
#endif

#include <godot_cpp/classes/${parentInc}.hpp>
#include <godot_cpp/core/binder_common.hpp>

using namespace godot;

class ${cls} : public ${parent} {
  GDCLASS(${cls}, ${parent});

protected:
  static void _bind_methods();

public:
  ${cls}();
  ~${cls}();
};
`;

  const classCpp = `#include "${cls}.h"

#include <godot_cpp/core/class_db.hpp>

using namespace godot;

void ${cls}::_bind_methods() {
}

${cls}::${cls}() {
}

${cls}::~${cls}() {
}
`;

  const registerH = `#pragma once

#include <godot_cpp/core/class_db.hpp>

using namespace godot;

void initialize_${lib}_module(ModuleInitializationLevel p_level);
void uninitialize_${lib}_module(ModuleInitializationLevel p_level);
`;

  const registerCpp = `#include "register_types.h"

#include <gdextension_interface.h>
#include <godot_cpp/core/class_db.hpp>
#include <godot_cpp/core/defs.hpp>
#include <godot_cpp/godot.hpp>

#include "${cls}.h"

using namespace godot;

void initialize_${lib}_module(ModuleInitializationLevel p_level) {
  if (p_level != MODULE_INITIALIZATION_LEVEL_SCENE) {
    return;
  }
  GDREGISTER_CLASS(${cls});
}

void uninitialize_${lib}_module(ModuleInitializationLevel p_level) {
  if (p_level != MODULE_INITIALIZATION_LEVEL_SCENE) {
    return;
  }
}

extern "C" {
GDExtensionBool GDE_EXPORT ${lib}_library_init(
    GDExtensionInterfaceGetProcAddress p_get_proc_address,
    GDExtensionClassLibraryPtr p_library,
    GDExtensionInitialization *r_initialization) {
  godot::GDExtensionBinding::InitObject init_obj(p_get_proc_address, p_library, r_initialization);
  init_obj.register_initializer(initialize_${lib}_module);
  init_obj.register_terminator(uninitialize_${lib}_module);
  init_obj.set_minimum_library_initialization_level(MODULE_INITIALIZATION_LEVEL_SCENE);
  return init_obj.init();
}
}
`;

  // Python .format() 的 {} 占位符在 TS 模板字面量里是字面字符,只有 ${...} 才插值。
  const sconstruct = `#!/usr/bin/env python
# Auto-generated by godot-mcp-enhanced cpp tool.
# Expects godot-cpp cloned to ./godot-cpp (see README.md).
env = SConscript("godot-cpp/SConstruct")

env.Append(CPPPATH=["src/"])
sources = Glob("src/*.cpp")

library = env.SharedLibrary(
    "bin/libgd${lib}{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
    source=sources,
)

env.NoCache(library)
Default(library)
`;

  const gdextension = `[configuration]

entry_symbol = "${lib}_library_init"
compatibility_minimum = "${ver}"

[libraries]
macos.debug = "res://bin/libgd${lib}.macos.template_debug.framework"
macos.release = "res://bin/libgd${lib}.macos.template_release.framework"
windows.debug.x86_64 = "res://bin/libgd${lib}.windows.template_debug.x86_64.dll"
windows.release.x86_64 = "res://bin/libgd${lib}.windows.template_release.x86_64.dll"
linux.debug.x86_64 = "res://bin/libgd${lib}.linux.template_debug.x86_64.so"
linux.release.x86_64 = "res://bin/libgd${lib}.linux.template_release.x86_64.so"
android.debug.arm64 = "res://bin/libgd${lib}.android.template_debug.arm64.so"
android.release.arm64 = "res://bin/libgd${lib}.android.template_release.arm64.so"
`;

  const gitignore = `# Build artifacts
bin/
*.o
*.obj

# godot-cpp dependency (cloned separately, see README.md)
godot-cpp/

# Godot editor cache
.godot/
`;

  // README 含 ``` 代码块与行内 `code`,在 TS 模板字面量里须转义反引号。
  const readme = `# ${cls} — GDExtension (Godot ${ver})

Auto-generated by **godot-mcp-enhanced** \`cpp\` tool.

## Build

1. Clone godot-cpp matching Godot **${ver}** into \`./godot-cpp\`:
   \`\`\`bash
   git clone -b godot-${ver}-stable https://github.com/godotengine/godot-cpp godot-cpp
   \`\`\`

2. Build the extension (produces \`bin/libgd${lib}.*\`):
   \`\`\`bash
   scons
   \`\`\`

3. In your Godot project, enable \`${lib}.gdextension\` (place or symlink this folder where Godot can reach it, then reload the project).

## Layout
- \`src/${cls}.h\` / \`${cls}.cpp\` — main class (extends ${parent})
- \`src/register_types.cpp\` / \`.h\` — module entry (\`${lib}_library_init\`)
- \`SConstruct\` — scons build (references \`./godot-cpp\`)
- \`${lib}.gdextension\` — Godot 4 extension descriptor
`;

  return [
    { path: `src/${cls}.h`, content: headerH },
    { path: `src/${cls}.cpp`, content: classCpp },
    { path: 'src/register_types.h', content: registerH },
    { path: 'src/register_types.cpp', content: registerCpp },
    { path: 'SConstruct', content: sconstruct },
    { path: `${lib}.gdextension`, content: gdextension },
    { path: '.gitignore', content: gitignore },
    { path: 'README.md', content: readme },
  ];
}
